apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-accelerate.fullname" . }}
  name: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
